title: "Daniela Grigori"
description: "Full Professor, Paris Dauphine â€“ PSL University"
theme: jekyll-theme-minimal

header_pages:
  - index.md
  - students.md
  - publications.md
  - projects.md
  - service.md
  - talks.md
