title: Daniela Grigori
theme: minima
markdown: kramdown

header_pages:
  - index.md
  - students.md
  - publications.md
  - projects.md
  - service.md
  - talks.md
  - tools.md
  - teaching.md
show_excerpts: false
footer:
  links: false
minima:
  social_links: false
