title: "Daniela Grigori"
description: "Full Professor, Paris Dauphine â€“ PSL University"
theme: minima
markdown: kramdown

header_pages:
  - index.md
  - students.md
  - publications.md
  - projects.md
  - service.md
  - talks.md
